config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users, :only => [:show]

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    delete 'logout', :to => 'devise/sessions#destroy'
    get 'register', :to => 'registrations#new'
    get 'settings', :to => 'devise/registrations#edit'
  end

  resources :articles do
  end

  resources :events do 
    collection do
      get :previous
      get :map
    end

    member do
      get :ics
    end
    resources :event_partners, :except => [:index, :show]
  end
  resources :partners, :only => [:index]
  resources :venues

  resources :entities
  resources :categories
  resources :tags

  get '/about', :to => 'static_pages#about', :as => 'about'
  get '/about/fact-sheet', :to => 'static_pages#fact_sheet', :as => 'fact_sheet'
  get '/about/officers', :to => 'static_pages#officers', :as => 'officers'
  get '/about/regional-chapters', :to => 'static_pages#chapters', :as => 'chapters'
  get '/devcon-events', :to => 'static_pages#events', :as => 'events_main'
  get '/devcon-events/request', :to => 'static_pages#request_event', :as => 'events_request'
  get '/keep-in-touch', :to => 'static_pages#keep_in_touch', :as => 'notifications'
  get '/contact', :to => 'static_pages#contact'
  get '/get-involved', :to => 'static_pages#get_involved', :as => 'get_involved'
  get '/get-involved/volunteer', :to => 'static_pages#volunteer', :as => 'volunteer'
  get '/get-involved/sponsor', :to => 'static_pages#sponsor', :as => 'sponsor'
  get '/faq', :to => 'static_pages#faq', :as => 'faq'
  get '/feed' => 'static_pages#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  get '/calendar.ics' => 'static_pages#calendar',
      :as => :calendar

  root :to => 'static_pages#home'
  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'static_pages#error_404'
  end
end

# == Route Map
#
#                   Prefix Verb     URI Pattern                                         Controller#Action
#                 ckeditor          /ckeditor                                           Ckeditor::Engine
#         new_user_session GET      /users/sign_in(.:format)                            devise/sessions#new
#             user_session POST     /users/sign_in(.:format)                            devise/sessions#create
#     destroy_user_session DELETE   /users/sign_out(.:format)                           devise/sessions#destroy
#  user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                     omniauth_callbacks#passthru {:provider=>/facebook/}
#   user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)              omniauth_callbacks#(?-mix:facebook)
#            user_password POST     /users/password(.:format)                           devise/passwords#create
#        new_user_password GET      /users/password/new(.:format)                       devise/passwords#new
#       edit_user_password GET      /users/password/edit(.:format)                      devise/passwords#edit
#                          PATCH    /users/password(.:format)                           devise/passwords#update
#                          PUT      /users/password(.:format)                           devise/passwords#update
# cancel_user_registration GET      /users/cancel(.:format)                             registrations#cancel
#        user_registration POST     /users(.:format)                                    registrations#create
#    new_user_registration GET      /users/sign_up(.:format)                            registrations#new
#   edit_user_registration GET      /users/edit(.:format)                               registrations#edit
#                          PATCH    /users(.:format)                                    registrations#update
#                          PUT      /users(.:format)                                    registrations#update
#                          DELETE   /users(.:format)                                    registrations#destroy
#                     user GET      /users/:id(.:format)                                users#show
#                    login GET      /login(.:format)                                    devise/sessions#new
#                   logout DELETE   /logout(.:format)                                   devise/sessions#destroy
#                 register GET      /register(.:format)                                 registrations#new
#                 settings GET      /settings(.:format)                                 devise/registrations#edit
#                 articles GET      /articles(.:format)                                 articles#index
#                          POST     /articles(.:format)                                 articles#create
#              new_article GET      /articles/new(.:format)                             articles#new
#             edit_article GET      /articles/:id/edit(.:format)                        articles#edit
#                  article GET      /articles/:id(.:format)                             articles#show
#                          PATCH    /articles/:id(.:format)                             articles#update
#                          PUT      /articles/:id(.:format)                             articles#update
#                          DELETE   /articles/:id(.:format)                             articles#destroy
#          previous_events GET      /events/previous(.:format)                          events#previous
#               map_events GET      /events/map(.:format)                               events#map
#                ics_event GET      /events/:id/ics(.:format)                           events#ics
#     event_event_partners POST     /events/:event_id/event_partners(.:format)          event_partners#create
#  new_event_event_partner GET      /events/:event_id/event_partners/new(.:format)      event_partners#new
# edit_event_event_partner GET      /events/:event_id/event_partners/:id/edit(.:format) event_partners#edit
#      event_event_partner PATCH    /events/:event_id/event_partners/:id(.:format)      event_partners#update
#                          PUT      /events/:event_id/event_partners/:id(.:format)      event_partners#update
#                          DELETE   /events/:event_id/event_partners/:id(.:format)      event_partners#destroy
#                   events GET      /events(.:format)                                   events#index
#                          POST     /events(.:format)                                   events#create
#                new_event GET      /events/new(.:format)                               events#new
#               edit_event GET      /events/:id/edit(.:format)                          events#edit
#                    event GET      /events/:id(.:format)                               events#show
#                          PATCH    /events/:id(.:format)                               events#update
#                          PUT      /events/:id(.:format)                               events#update
#                          DELETE   /events/:id(.:format)                               events#destroy
#                 partners GET      /partners(.:format)                                 partners#index
#                   venues GET      /venues(.:format)                                   venues#index
#                          POST     /venues(.:format)                                   venues#create
#                new_venue GET      /venues/new(.:format)                               venues#new
#               edit_venue GET      /venues/:id/edit(.:format)                          venues#edit
#                    venue GET      /venues/:id(.:format)                               venues#show
#                          PATCH    /venues/:id(.:format)                               venues#update
#                          PUT      /venues/:id(.:format)                               venues#update
#                          DELETE   /venues/:id(.:format)                               venues#destroy
#                 entities GET      /entities(.:format)                                 entities#index
#                          POST     /entities(.:format)                                 entities#create
#               new_entity GET      /entities/new(.:format)                             entities#new
#              edit_entity GET      /entities/:id/edit(.:format)                        entities#edit
#                   entity GET      /entities/:id(.:format)                             entities#show
#                          PATCH    /entities/:id(.:format)                             entities#update
#                          PUT      /entities/:id(.:format)                             entities#update
#                          DELETE   /entities/:id(.:format)                             entities#destroy
#               categories GET      /categories(.:format)                               categories#index
#                          POST     /categories(.:format)                               categories#create
#             new_category GET      /categories/new(.:format)                           categories#new
#            edit_category GET      /categories/:id/edit(.:format)                      categories#edit
#                 category GET      /categories/:id(.:format)                           categories#show
#                          PATCH    /categories/:id(.:format)                           categories#update
#                          PUT      /categories/:id(.:format)                           categories#update
#                          DELETE   /categories/:id(.:format)                           categories#destroy
#                     tags GET      /tags(.:format)                                     tags#index

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @articles = Article.where(:draft => false).limit(3)
    if Event.upcoming.include_subevents.count > 0
      @events = Event.upcoming.include_subevents.limit(3)
      @events_type = "Upcoming Events"
    elsif Event.finished.include_subevents.count > 0
      @events = Event.finished.include_subevents.limit(3)
      @events_type = "Previous Events"
    else
      @events = []
      @events_type = "No Events Yet"
    end
  end

  def contact
  end

  def feed
    @title = "Developers Connect Philippines"
    @entries = 
      (Event.include_subevents.all + Article.all)
      .sort_by(&:updated_at).reverse
    @updated = unless @entries.empty?
      @entries.first.updated_at
    else
      DateTime.now
    end
    respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end

  def calendar
    cal = Icalendar::Calendar.new
    cal.timezone { |tz| tz.tzid = "Asia/Manila" }
    cal.x_wr_calname = "DevCon Calendar of Events"

    Event.all.each do |event_temp|
      url = event_url(event_temp)
      cal.event do |e|
        e.dtstart = event_temp.start_at.strftime("%Y%m%dT%H%M00")
        e.dtend = event_temp.end_at.strftime("%Y%m%dT%H%M00")
        e.dtstamp = event_temp.updated_at.strftime("%Y%m%dT%H%M00")
        e.uid = "#{event_temp.slug}@devcon.ph"
        e.summary = event_temp.name
        e.description = (event_temp.summary || "") + " " + url
        e.ip_class = 'PUBLIC'
        e.url = url
      end
    end
    send_data cal.to_ical, filename: "calendar.ics", type: 'text/calendar', x_sendfile: true
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_about_sidebar.html.erb
<div class="col-sm-3 sidebar-nav hidden-xs">
  <ul id="sidebar">
    <li class='<%= "active" if selected == 'top' %>'><%= link_to 'About DevCon', about_path %></li>
    <li class='<%= "active" if selected == 'fact_sheet' %>'><%= link_to 'Fact Sheet', fact_sheet_path %></li>
    <li class='<%= "active" if selected == 'officers' %>'><%= link_to 'Officers', officers_path %></li>
    <li class='<%= "active" if selected == 'chapters' %>'><%= link_to 'Regional Chapters', chapters_path %></li>
    <li><%= link_to 'Articles', articles_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
  </ul>
</div>

app/views/static_pages/_events_sidebar.html.erb
<div class="col-sm-3 sidebar-nav hidden-xs">
  <ul id="sidebar">
    <li class='<%= "active" if selected == 'top' %>'><%= link_to 'DevCon Events', events_main_path %></li>
    <li><%= link_to 'List of Upcoming Events', events_path %></li>
    <li class='<%= "active" if selected == 'request' %>'><%= link_to 'Request an Event', events_request_path %></li>
    <li><%= link_to 'Past Events Photo Gallery', 'https://www.facebook.com/DevConPH/photos_stream' %></li>
  </ul>
</div>

app/views/static_pages/_gi_sidebar.html.erb
<div class="col-sm-3 sidebar-nav hidden-xs">
  <ul id="sidebar">
    <li class='<%= "active" if selected == 'top' %>'><%= link_to 'Get Involved', get_involved_path %></li>
    <li class='<%= "active" if selected == 'volunteer' %>'><%= link_to 'Become a Volunteer', volunteer_path %></li>
    <li class='<%= "active" if selected == 'sponsor' %>'><%= link_to 'Sponsor Events', sponsor_path %></li>
    <%#<li><a href="#">Donate</a></li>%>
    <li><%= link_to 'Fork this on Github', 'https://github.com/devcon-ph/devcon' %></li>
  </ul>
</div>

app/views/static_pages/about.html.erb
<% title 'About DevCon' %>
<% description "Developers Connect Philippines (DevCon) is a non-proﬁt organization which aims to promote the \"IT Pinoy Talent\" mainly by providing a unique venue for IT students, educators, professionals and enthusiasts to Sync, Support and Succeed." %>
<% set_meta_tags :open_graph => {
  :title => "#{ENV['title']} | Frequently Asked Questions",
  :description => "Developers Connect Philippines (DevCon) is a non-proﬁt organization which aims to promote the \"IT Pinoy Talent\" mainly by providing a unique venue for IT students, educators, professionals and enthusiasts to Sync, Support and Succeed.",
  :type  => :website,
  :url   => about_url,
  :image => [opengraph_thumb_url, { :width => 200, :height => 200 }]
} %>
<div class="row faq">
  <div class="col-sm-9">
    <h1>About DevCon</h1>

    <p>Developers Connect Philippines (DevCon) is a BIR and SEC registered non-profit, non-government organization which aims to empower Filipino developers and promote the "IT Pinoy Talent" by providing unique venues for IT students, educators, professionals and enthusiasts to <em>Sync, Support and Succeed</em>.</p>

    <h2>History</h2>

    <p>DevCon was founded in June 26, 2009.</p>

    <p>DevCon is a pioneering project of the Philippine Software Industry Association (PSIA). Its pilot event, DevCon Visayas, was held at the TechBar in Cebu City. DevCon also spanned a ten-city nationwide tour as part of the Next Wave Cities roadshow run by the then Commission on Information and Communications Technology (CICT) and Business Processing Association of the Philippines (BPA/P) in 2009.</p>

    <p>To increase its reach, DevCon has signed a partnership with the Philippine Society of IT Educators (PSITE) to make DevCon accessible to IT students nationwide. Furthermore, to ensure that DevCon's presence will continue to grow, DevCon registered under the Securities and Exchange Commission as a non-profit organization.</p>

    <h2>DevCon's Achievements</h2>
    <p>DevCon is the youngest yet most comprehensive IT capabilities development organization in the Philippines. Known for hosting free <em>unconferences</em> for IT students, educators, professionals and enthusiasts, DevCon has grown to having over <em>20,000</em> participants since June 2009. It is highly sought after by educational institutions through its campus DevCon programs that aim to augment the academic learnings of students with up-to-date trends in the IT industry.</p>

    <p>Aside from its regular activities, DevCon also organizes special events that promote the IT industry. Two of the big special events so far are the Hack2Hatch: From Hacker to Founder and DevCon Code Challenge Cup (C-Cup).</p>
    
    <p><em>Hack2HATCH: From Hacker to Founder</em> was co-organized DevCon and PhilDev, a non-profit that promotes tech innovation in the Philippines. Hack2Hatch was a technopreneurship event in Cebu City held last 05-07 October 2012 in Radisson Blu Hotel and Mactan Shangri-La Resort where 22 Philippine startups competed to be among the top 8 teams to each get <em><%= number_to_currency 100000.00 %></em> in funding. Mentors and judges included Silicon Valley entrepreneurs, PhilDev board and trustees, and top businessmen in the country.</p>

    <div class="row hack2hatch-row">
      <div class="col-lg-10 col-md-10 col-sm-10 col-sm-offset-1">
        <div class="thumbnail h2h-faq">
          <%= image_tag "faq/h2h.jpg", :alt => "Hack2HATCH" %>
          <div class="caption"><a href="http://www.hack2hatch.com/" target="_blank">Hack2HATCH</a> Winners, Mentors and Judges at the Mactan Shangri-La Resort</div>
        </div>
      </div>
    </div>

    <p><em>DevCon Code Challenge Cup (C-Cup)</em>, held on November 2012, was a national algorithm programming competition mixed with the dexterity of a hackathon with over 45 high school, collegiate and professional teams participated in the event.</p>
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8 col-sm-offset-2">
        <div class="thumbnail ccup">
          <%= image_tag "faq/ccup.jpg", :alt => "Code Challenge Cup" %>
          <div class="caption"><a href="http://devcon.ph/events/devcon-code-challenge-cup-c-cup" target="_blank">DevCon–Xavier Code Challenge Cup (C-Cup)</a></div>
        </div>
      </div>
    </div>
    <p>In the recent years, DevCon has also received the following awards and grants:</p>
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8 col-sm-offset-2">
        <div class="thumbnail ccup">
          <%= image_tag "MSF-Grant-Awardee.jpg", :alt => "Motorola Solutions Foundation Grant Awardee" %>
        </div>
        <div class="thumbnail ccup">
          <%= image_tag "ICT-MAS-Award.jpg", :alt => "CdO ICT Business Council Movers and Shakers Award" %>
        </div>
      </div>
    </div>
  </div>
  <%= render :partial => 'about_sidebar', :locals => { :selected => 'top' } %>
</div>

app/views/static_pages/error_500.html.erb
<% title 'Error 500' %>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <h1>Error 500</h1>
    <p>Something went wrong with processing your request.</p>
    <p>If you keep seeing this page, inform <a href="mailto:bry@devcon.ph">Bry</a> ASAP. In the meantime, here's Nyan Cat to keep you company:</p>
    <div class="embed-responsive embed-responsive-16by9">
      <iframe width="560" height="315" src="http://www.youtube-nocookie.com/embed/QH2-TGUlwu4?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>
    <p><%= link_to "Go back to homepage", root_url %></p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% description "Developers Connect Philippines (DevCon) is a non-proﬁt organization which aims to promote the \"IT Pinoy Talent\" mainly by providing a unique venue for IT students, educators, professionals and enthusiasts to Sync, Support and Succeed." %>
<% set_meta_tags :open_graph => {
  :title => "#{ENV['title']}",
  :description => "Developers Connect Philippines (DevCon) is a non-proﬁt organization which aims to promote the \"IT Pinoy Talent\" mainly by providing a unique venue for IT students, educators, professionals and enthusiasts to Sync, Support and Succeed.",
  :type  => :website,
  :url   => root_url,
  :image => [opengraph_thumb_url, { :width => 200, :height => 200 }]
} %>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-12">
      <h1>
        <%= link_to root_path do %>
          <%= image_tag "logo.png", :title => "Developers Connect", :class => 'long' %>
        <% end %> 
      </h1>
      <p class="blurb"><strong>Developers Connect Philippines (DevCon)</strong> is a non-proﬁt organization which aims to promote the "IT Pinoy Talent" mainly by providing a unique venue for IT students, educators, professionals and enthusiasts to <em>Sync, Support and Succeed.</em></p>
    </div>
    <div class="col-md-12 avp">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe width="560" height="315" src="//www.youtube-nocookie.com/embed/hMwDI_nv5xU?rel=0" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="support-options">
  <div class="row">
    <div class="col-sm-12"><h3>How you can get involved with DevCon:</h3></div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-2">
      <%= image_tag 'volunteer.jpg', :class => "img-thumbnail" %>
      <h3>Be a Volunteer</h3>
      <p>Pick up new skills and make new friends. We have many volunteer opportunities for students and professionals.</p>
      <p><%= link_to "Volunteer &raquo;".html_safe, volunteer_path, :class => "btn btn-default btn-success btn-lg" %></p>
    </div>
    <div class="col-sm-6 col-md-4">
      <%= image_tag 'sponsor.jpg', :class => "img-thumbnail" %>
      <h3>Sponsor Events</h3>
      <p>DevCon events are free and are made possible by the generous support from the community.</p>
      <p><%= link_to "Sponsor &raquo;".html_safe, sponsor_path, :class => "btn btn-default btn-success btn-lg" %></p>
    </div>
  </div>
</div>
<div class="row partner-area">
  <div class="col-sm-12">
    <h2>Platinum Partners</h2>
    <p class="partner-list clearfix">
      <a href="http://www.exist.com/"><%= image_tag "exist.png", :alt => "Exist" %></a>
      <a href="http://acale.ph/"><%= image_tag "acaleph.png", :alt => "Acaleph" %></a>
      <a href="http://microsoft.com/philippines/"><%= image_tag "microsoft.jpg", :alt => "Microsoft Philippines" %></a>
    </p>
  </div>
</div>
<div class="row frontpage-lists">
  <div class="col-md-6 events">
    <h2><%= @events_type %></h2>
    <% @events.each do |event| %>
      <div class="row">
        <div class="col-sm-2 col-md-3 col-lg-2">
          <%= image_tag event.logo.small %>
        </div>
        <div class="col-sm-10 col-md-9 col-lg-10">
          <h3><%= link_to event.name, event, :class => 'title' %></h3>
          <p><small>
            <%= l(event.start_at, :format => :long) %> 
            <% if event.start_at.future? %>
              (<%= distance_of_time_in_words_to_now event.start_at %> from now)
            <% else %>
              to
              <%= l(event.end_at, :format => :long) %> 
            <% end %>
          </small></p>
        </div>
      </div>
    <% end %>
    <p><%= link_to "View full list of Events &raquo".html_safe, events_path, :class => "btn btn-success btn-lg" %></p>
  </div>
  <div class="col-md-6 articles">
    <h2>Latest Articles</h2>
    <% @articles.each do |article| %>
      <div class="row">
        <div class="col-sm-2 col-md-3 col-lg-2">
          <%= image_tag article.thumbnail.small %>
        </div>
        <div class="col-sm-10 col-md-9 col-lg-10">
          <h3><%= link_to article.title, article, :class => 'title' %></h3>
          <p><small>
            <%= l(article.updated_at, :format => "%b %d, %Y") %> 
          </small></p>
        </div>
      </div>
    <% end %>
    <p><%= link_to "View other Articles &raquo".html_safe, articles_path, :class => "btn btn-success btn-lg" %></p>
  </div>
</div>
<hr>
<div class="row frontpage-lists">
  <div class="col-md-6 frontpage-twitter">
    <a class="twitter-timeline" href="https://twitter.com/DevConPH" data-widget-id="309122045189427200">Tweets by @DevConPH</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
  <div class="col-md-6 frontpage-twitter">
    <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fdevconph&amp;width&amp;height=427&amp;colorscheme=light&amp;show_faces=false&amp;header=true&amp;stream=true&amp;show_border=true&amp;appId=488047311326879" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:400px; width:100%" allowTransparency="true"></iframe>
  </div>
</div>

app/views/static_pages/speaker.html.erb
<% title "Become a Speaker" %>
<% description "Share your knowledge and experiences in the IT industry through short lightning talks or day-long workshops." %>
<% set_meta_tags :open_graph => {
  :title => "Become a Speaker | #{ENV['title']}",
  :description => "Share your knowledge and experiences in the IT industry through short lightning talks or day-long workshops.",
  :type  => :article,
  :url   => volunteer_url,
  :image => opengraph_thumb_url
} %>
<div class="row faq">
  <div class="col-sm-9">
    <h1>Become a Speaker</h1>
    <div class="row">
      <div class="col-lg-10 col-md-12 col-lg-offset-1">
        <div class="thumbnail">
          <%= image_tag "speaker.jpg", :alt => "Become a Speaker" %>
        </div>
      </div>
    </div>
    <h2>Lightning Talks</h2>
    <p>Lightning talks are 10-15 minute talks presented during <%= link_to "Campus DevCons", events_main_path %>. They can be about anything related to IT: from highly technical CS topics, to project management, to career advice.</p>

    <p>Here are some quick tips for prospective lightning speakers:</p>

    <ul>
      <li>Keep in mind that most of your audience will be students. Make your talk too technical and they'll zone off, make it too shallow and they won't learn anything.</li>
      <li>You have a short time to present. It's much better to have 3-4 main points that you can explain in detail rather than have 10+ points but be cut off by the time limit.</li>
      <li>Slides are optional but are recommended as they can guide both you and your audience on the flow of the talk.</li>
      <li>If you choose to make use of slides, learn to be creative with them. Nothing shuts off a students attention than slides full of bullet points and text. Switch around with text (ie. the 1-6-6 rule) and pictures to keep your audience on their feet.</li>
    </ul>

    <p>One quick thing to note about Campus DevCons is that most of them are conducted on <em>weekdays</em>. This means that we're looking for speakers who are willing to take a leave from their work to share a bit of their knowledge to students. (Of course, freelancers and flexi-time employees can just take an hour or so off work to give their talk and go back to work afterwards.)

    <h2>Code Camps</h2>
    <p>Code Camps are workshops which introduce technologies (e.g. <a href="http://devcon.ph/events/4th-devcon-android-code-camp-professionals">Android</a>, <a href="http://devcon.ph/events/git-code-camp-for-professionals">Git</a>) or processes (e.g. <a href="http://devcon.ph/events/project-management-camp-scrum-methodology">Scrum</a>) to interested students and professionals. Code Camps require more preparation for both DevCon and the speakers so they are not as common as Campus DevCons.</p>

    <p>Individuals interested to be a mentor or instructor in Code Camps only need to sign up as a speaker in the form linked below. We will inform you once such an opportuntity arises.</p>

    <p>Companies or community groups who wish to hold a Code Camp in partnership with DevCon can refer to <%= link_to "Request an Event", events_request_path %> for details.</p>

    <h2>Sign up as a Speaker</h2>

    <p>As Speakers are practically <%= link_to "Volunteers", volunteer_path %>, the former also uses the same sign-up form as the latter.</p>

    <p><%= link_to "Sign up as a Speaker &raquo;".html_safe, "https://docs.google.com/a/devcon.ph/forms/d/1i-rhXPwGKFBSMgZNkcnzYVs-ZHOQA-Ao9Hu3j8T2wbM/viewform", :class => "btn btn-default btn-success btn-lg" %></p>

    <p>To know more about becoming a speaker, email our VP for Technology via <a href="mailto:terence@devcon.ph">terence@devcon.ph</a>.</p>
  </div>
  <%= render :partial => 'gi_sidebar', :locals => { :selected => 'speaker' } %>
</div>

app/views/static_pages/sponsor.html.erb
<% title "Sponsor Events" %>
<% description "DevCon events are free and are made possible by the generous support from the community. Here's how you can sponsor events." %>
<% set_meta_tags :open_graph => {
  :title => "#{ENV['title']} | Sponsor Events",
  :description => "DevCon events are free and are made possible by the generous support from the community. Here's how you can sponsor events.",
  :type  => :website,
  :url   => sponsor_url,
  :image => [opengraph_thumb_url, { :width => 200, :height => 200 }]
} %>
<div class="row faq">
  <div class="col-sm-9">

    <h1>Sponsor Events</h1>

    <div class="row">
      <div class="col-xs-12">
        <div class="thumbnail">
          <%= image_tag "sponsorships.jpg", :alt => "Sponsorships" %>
        </div>
      </div>
    </div>

    <p>DevCon events are free with the support from the community to fund event expenses. Sponsorships fall into two categories:</p>

    <dl>
      <dt>Quarterly Partnerships</dt>
      <dd>Among the benefits of a quarterly partner are brand exposure online and offline, speakership opportunities to Campus DevCon and Code Camp events conducted all throughout the country, and special partnership events.</dd>
    </dl>

    <dl>
      <dt>Per Event Sponsorship</dt>
      <dd>There are cases when sponsoring per event is the best approach especially when the audience is more targeted. Among the benefits are speakership opportunities, brand offline and online exposure and special activity before or during the event.</dd>
    </dl>

    <p>Sponsorships may be in monetary form or in-kind. Here are a few examples of the latter:</p>

    <ul>
      <li><strong>Venues</strong> - share your meeting or training rooms for <%= link_to 'Code Camps', events_main_path %></li>
      <li><strong>Food</strong> - for Code Camps and larger events</li>
      <li><strong>Giveaways</strong> - t-shirts, stickers, and other small tokens for attendees</li>
    </ul>

    <p>To learn more about sponsorships, email our VP Finance via <a href="mailto:jossi@devcon.ph">jossie@devcon.ph</a>.</p>
  </div>
  <%= render :partial => 'gi_sidebar', :locals => { :selected => 'sponsor' } %>
</div>