config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users, :only => [:show]

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    delete 'logout', :to => 'devise/sessions#destroy'
    get 'register', :to => 'registrations#new'
    get 'settings', :to => 'devise/registrations#edit'
  end

  resources :articles do
  end

  resources :events do 
    collection do
      get :previous
      get :map
    end

    member do
      get :ics
    end
    resources :event_partners, :except => [:index, :show]
  end
  resources :partners, :only => [:index]
  resources :venues

  resources :entities
  resources :categories
  resources :tags

  get '/about', :to => 'static_pages#about', :as => 'about'
  get '/about/fact-sheet', :to => 'static_pages#fact_sheet', :as => 'fact_sheet'
  get '/about/officers', :to => 'static_pages#officers', :as => 'officers'
  get '/about/regional-chapters', :to => 'static_pages#chapters', :as => 'chapters'
  get '/devcon-events', :to => 'static_pages#events', :as => 'events_main'
  get '/devcon-events/request', :to => 'static_pages#request_event', :as => 'events_request'
  get '/keep-in-touch', :to => 'static_pages#keep_in_touch', :as => 'notifications'
  get '/contact', :to => 'static_pages#contact'
  get '/get-involved', :to => 'static_pages#get_involved', :as => 'get_involved'
  get '/get-involved/volunteer', :to => 'static_pages#volunteer', :as => 'volunteer'
  get '/get-involved/sponsor', :to => 'static_pages#sponsor', :as => 'sponsor'
  get '/faq', :to => 'static_pages#faq', :as => 'faq'
  get '/feed' => 'static_pages#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  get '/calendar.ics' => 'static_pages#calendar',
      :as => :calendar

  root :to => 'static_pages#home'
  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'static_pages#error_404'
  end
end

# == Route Map
#
#                   Prefix Verb     URI Pattern                                         Controller#Action
#                 ckeditor          /ckeditor                                           Ckeditor::Engine
#         new_user_session GET      /users/sign_in(.:format)                            devise/sessions#new
#             user_session POST     /users/sign_in(.:format)                            devise/sessions#create
#     destroy_user_session DELETE   /users/sign_out(.:format)                           devise/sessions#destroy
#  user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                     omniauth_callbacks#passthru {:provider=>/facebook/}
#   user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)              omniauth_callbacks#(?-mix:facebook)
#            user_password POST     /users/password(.:format)                           devise/passwords#create
#        new_user_password GET      /users/password/new(.:format)                       devise/passwords#new
#       edit_user_password GET      /users/password/edit(.:format)                      devise/passwords#edit
#                          PATCH    /users/password(.:format)                           devise/passwords#update
#                          PUT      /users/password(.:format)                           devise/passwords#update
# cancel_user_registration GET      /users/cancel(.:format)                             registrations#cancel
#        user_registration POST     /users(.:format)                                    registrations#create
#    new_user_registration GET      /users/sign_up(.:format)                            registrations#new
#   edit_user_registration GET      /users/edit(.:format)                               registrations#edit
#                          PATCH    /users(.:format)                                    registrations#update
#                          PUT      /users(.:format)                                    registrations#update
#                          DELETE   /users(.:format)                                    registrations#destroy
#                     user GET      /users/:id(.:format)                                users#show
#                    login GET      /login(.:format)                                    devise/sessions#new
#                   logout DELETE   /logout(.:format)                                   devise/sessions#destroy
#                 register GET      /register(.:format)                                 registrations#new
#                 settings GET      /settings(.:format)                                 devise/registrations#edit
#                 articles GET      /articles(.:format)                                 articles#index
#                          POST     /articles(.:format)                                 articles#create
#              new_article GET      /articles/new(.:format)                             articles#new
#             edit_article GET      /articles/:id/edit(.:format)                        articles#edit
#                  article GET      /articles/:id(.:format)                             articles#show
#                          PATCH    /articles/:id(.:format)                             articles#update
#                          PUT      /articles/:id(.:format)                             articles#update
#                          DELETE   /articles/:id(.:format)                             articles#destroy
#          previous_events GET      /events/previous(.:format)                          events#previous
#               map_events GET      /events/map(.:format)                               events#map
#                ics_event GET      /events/:id/ics(.:format)                           events#ics
#     event_event_partners POST     /events/:event_id/event_partners(.:format)          event_partners#create
#  new_event_event_partner GET      /events/:event_id/event_partners/new(.:format)      event_partners#new
# edit_event_event_partner GET      /events/:event_id/event_partners/:id/edit(.:format) event_partners#edit
#      event_event_partner PATCH    /events/:event_id/event_partners/:id(.:format)      event_partners#update
#                          PUT      /events/:event_id/event_partners/:id(.:format)      event_partners#update
#                          DELETE   /events/:event_id/event_partners/:id(.:format)      event_partners#destroy
#                   events GET      /events(.:format)                                   events#index
#                          POST     /events(.:format)                                   events#create
#                new_event GET      /events/new(.:format)                               events#new
#               edit_event GET      /events/:id/edit(.:format)                          events#edit
#                    event GET      /events/:id(.:format)                               events#show
#                          PATCH    /events/:id(.:format)                               events#update
#                          PUT      /events/:id(.:format)                               events#update
#                          DELETE   /events/:id(.:format)                               events#destroy
#                 partners GET      /partners(.:format)                                 partners#index
#                   venues GET      /venues(.:format)                                   venues#index
#                          POST     /venues(.:format)                                   venues#create
#                new_venue GET      /venues/new(.:format)                               venues#new
#               edit_venue GET      /venues/:id/edit(.:format)                          venues#edit
#                    venue GET      /venues/:id(.:format)                               venues#show
#                          PATCH    /venues/:id(.:format)                               venues#update
#                          PUT      /venues/:id(.:format)                               venues#update
#                          DELETE   /venues/:id(.:format)                               venues#destroy
#                 entities GET      /entities(.:format)                                 entities#index
#                          POST     /entities(.:format)                                 entities#create
#               new_entity GET      /entities/new(.:format)                             entities#new
#              edit_entity GET      /entities/:id/edit(.:format)                        entities#edit
#                   entity GET      /entities/:id(.:format)                             entities#show
#                          PATCH    /entities/:id(.:format)                             entities#update
#                          PUT      /entities/:id(.:format)                             entities#update
#                          DELETE   /entities/:id(.:format)                             entities#destroy
#               categories GET      /categories(.:format)                               categories#index
#                          POST     /categories(.:format)                               categories#create
#             new_category GET      /categories/new(.:format)                           categories#new
#            edit_category GET      /categories/:id/edit(.:format)                      categories#edit
#                 category GET      /categories/:id(.:format)                           categories#show
#                          PATCH    /categories/:id(.:format)                           categories#update
#                          PUT      /categories/:id(.:format)                           categories#update
#                          DELETE   /categories/:id(.:format)                           categories#destroy
#                     tags GET      /tags(.:format)                                     tags#index

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  content      :text
#  author_id    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  slug         :string(255)
#  summary      :text
#  thumbnail    :string(255)
#  published    :boolean          default(FALSE)
#  published_at :datetime
#

include ActionView::Helpers::SanitizeHelper

class Article < ActiveRecord::Base
  belongs_to :author, :class_name => 'User', :foreign_key => 'author_id'
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :tags
  has_many :comments, :as => :commentable

  validates :title, :presence => true
  validates :content, :presence => true
  validates :author_id, :presence => true
  validates_presence_of :slug
  validates_uniqueness_of :slug

  default_scope -> { order('articles.created_at DESC') }

  before_validation :generate_slug, :generate_summary

  mount_uploader :thumbnail, ThumbnailUploader

  def generate_slug
    self.slug ||= title.to_slug.normalize.to_s
  end

  def generate_summary
    if self.summary.blank?
      self.summary = strip_tags(content)
    end
  end

  def to_param
    slug
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :paginate_articles, :only => :index
  load_resource :find_by => :slug
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @article.author = current_user
    if @article.save
      flash[:success] = 'Successfully published an article.'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    params[:article][:category_ids] ||= []

    if @article.update_attributes(article_params)
      flash[:success] = 'Article has been updated!'
      redirect_to @article
    else
      render :action => 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Successfully destroyed article'
    redirect_to articles_path
  end

  private

    def paginate_articles
      query = if user_signed_in? && (current_user.role?(:admin) ||
                                     current_user.role?(:author))
                Article.all
              else
                Article.where(:draft => false)
              end
      @articles = query.paginate(:page => params[:page])
    end

    def article_params
      params.require(:article).permit(:title, :draft, :content, { :category_ids => []}, :slug, :thumbnail, :summary)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="row article">
  <div class="col-md-2 col-sm-3">
    <%= image_tag article.thumbnail.thumb %>
  </div>
  <div class="col-md-10 col-sm-9">
    <h2><%= link_to article.title, article, :class => 'title' %></h2>
    <p><small>
      <%= l(article.created_at, :format => :friendly_date) %> 
      | by
      <% if article.author.name.blank? %>
        <%= link_to article.author.email, article.author %>
      <% else %>
        <%= link_to article.author.name, article.author %>
      <% end %>
      |
      <%= link_to "", article_url(article) + "#disqus_thread" %>
      <% if article.draft? %>
        |
        <span class="label label-info">draft</span>
      <% end %>
    </small></p>
    <p class="summary">
      <%= article.summary %>
      <% if can? :update, article %>
        <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-default btn-xs" %>
      <% end %>
      <% if can? :destroy, article %>
        <%= link_to 'Destroy', article_path(article), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => "btn btn-danger btn-xs" %>
      <% end %>
    <p>
  </div>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article,
    :wrapper_mappings => {
      :check_boxes => :vertical_radio_and_checkboxes,
      :radio_buttons => :vertical_radio_and_checkboxes,
      :file => :vertical_file_input,
      :boolean => :vertical_boolean }) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <%= f.input :title %>
  <% unless @article.slug.blank? %>
    <%= f.input :slug, :hint => "For permalink" %>
  <% end %>

  <%= f.input :draft, :hint => "Draft articles will not be shown to the public" %>

  <%= render :partial => "shared/view_thumbnail", :locals => { :obj => @article } %>
  <%= f.input :thumbnail, :as => :file %>
  <%= f.input :content,
              :as => :ckeditor %>
  <%= f.input :summary, :input_html => { class: 'input-xxlarge editor-html', size: "500x6" }, :hint => "A shorter description for use in places where the full description would be overkill." %>
  <%= f.association :categories, :as => :check_boxes %>

  <div class="form-actions">
    <%= f.button :submit,
                 :class => 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% title 'Edit article' %>
<h1>Edit article</h1>

<%= render 'form' %>
<%= link_to 'Back to articles', articles_path %>

app/views/articles/index.html.erb
<% title 'Articles' %>
<% description "News, articles, and random blog posts from our members." %>
<% set_meta_tags :open_graph => {
  :title => "Articles | #{ENV['title']}",
  :description => "News, articles, and random blog posts from our members.",
  :type  => :article,
  :url   => articles_url,
  :image => [opengraph_thumb_url, { :width => 200, :height => 200 }]
} %>
<h1>Articles</h1>
<% if can? :create, Article %>
  <p>
  <%= link_to 'New article', new_article_path, :class => "btn btn-default" %>
  </p>
<% end %>

<%= render @articles %>

<%= will_paginate %>

<%= render :partial => "shared/disqus_count" %>

app/views/articles/new.html.erb
<% title 'New article' %>
<h1>New article</h1>

<%= render 'form' %>
<%= link_to 'Back to articles', articles_path %>

app/views/articles/show.html.erb
<% title @article.title %>
<% description generate_description(@article.summary) %>
<% set_meta_tags :open_graph => {
  :title => "#{@article.title} | #{ENV['title']}",
  :description => generate_description(@article.summary),
  :type  => :article,
  :url   => article_url(@article),
  :image => [thumbnail_url(@article), { :width => 200, :height => 200 }]
} %>

<div class="row article">
  <% cache [@article, "top"] do %>
  <div class="col-lg-2 col-md-2">
    <%= image_tag @article.thumbnail.thumb %>
  </div>
  <div class="col-lg-10 col-md-10">
    <h1><%= link_to @article.title, @article, :class => 'title' %></h1>
    <p><small>
      <%= l(@article.created_at, :format => :friendly_date) %> 
      | by
      <% if @article.author.name.blank? %>
        <%= link_to @article.author.email, @article.author %>
      <% else %>
        <%= link_to @article.author.name, @article.author %>
      <% end %>
      |
      <% if @article.categories.any? %>
        <%= @article.categories.count == 1 ? 'Category' : 'Category'.pluralize %>: 
        <% @article.categories.each do |category| %>
          <%= link_to category.name, category %> 
        <% end %>
      <% end %>
      <% if @article.draft? %>
        |
        <span class="label label-info">draft</span>
      <% end %>
    </small></p>
    <div class="article-content">
      <%= raw @article.content %>
      <p>
        <%= link_to 'Back to articles', articles_path, :class => "btn btn-default" %>
  <% end %>
        <% if can? :update, @article %>
          <%= link_to 'Edit', edit_article_path(@article), :class => "btn btn-default" %>
        <% end %>
        <% if can? :destroy, @article %>
          <%= link_to 'Destroy', article_path(@article), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => "btn btn-danger" %>
        <% end %>
  <% cache [@article, "bottom"] do %>
      </p>
    </div>
    <div class="row social-sharing">
      <%= render "shared/social_sharing" %>
    </div>
    <div id="disqus_thread"></div>
  </div>
</div>

<%= render :partial => "shared/disqus_comments" %>
  <% end %>