config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users, :only => [:show]

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    delete 'logout', :to => 'devise/sessions#destroy'
    get 'register', :to => 'registrations#new'
    get 'settings', :to => 'devise/registrations#edit'
  end

  resources :articles do
  end

  resources :events do 
    collection do
      get :previous
      get :map
    end

    member do
      get :ics
    end
    resources :event_partners, :except => [:index, :show]
  end
  resources :partners, :only => [:index]
  resources :venues

  resources :entities
  resources :categories
  resources :tags

  get '/about', :to => 'static_pages#about', :as => 'about'
  get '/about/fact-sheet', :to => 'static_pages#fact_sheet', :as => 'fact_sheet'
  get '/about/officers', :to => 'static_pages#officers', :as => 'officers'
  get '/about/regional-chapters', :to => 'static_pages#chapters', :as => 'chapters'
  get '/devcon-events', :to => 'static_pages#events', :as => 'events_main'
  get '/devcon-events/request', :to => 'static_pages#request_event', :as => 'events_request'
  get '/keep-in-touch', :to => 'static_pages#keep_in_touch', :as => 'notifications'
  get '/contact', :to => 'static_pages#contact'
  get '/get-involved', :to => 'static_pages#get_involved', :as => 'get_involved'
  get '/get-involved/volunteer', :to => 'static_pages#volunteer', :as => 'volunteer'
  get '/get-involved/sponsor', :to => 'static_pages#sponsor', :as => 'sponsor'
  get '/faq', :to => 'static_pages#faq', :as => 'faq'
  get '/feed' => 'static_pages#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  get '/calendar.ics' => 'static_pages#calendar',
      :as => :calendar

  root :to => 'static_pages#home'
  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'static_pages#error_404'
  end
end

# == Route Map
#
#                   Prefix Verb     URI Pattern                                         Controller#Action
#                 ckeditor          /ckeditor                                           Ckeditor::Engine
#         new_user_session GET      /users/sign_in(.:format)                            devise/sessions#new
#             user_session POST     /users/sign_in(.:format)                            devise/sessions#create
#     destroy_user_session DELETE   /users/sign_out(.:format)                           devise/sessions#destroy
#  user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                     omniauth_callbacks#passthru {:provider=>/facebook/}
#   user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)              omniauth_callbacks#(?-mix:facebook)
#            user_password POST     /users/password(.:format)                           devise/passwords#create
#        new_user_password GET      /users/password/new(.:format)                       devise/passwords#new
#       edit_user_password GET      /users/password/edit(.:format)                      devise/passwords#edit
#                          PATCH    /users/password(.:format)                           devise/passwords#update
#                          PUT      /users/password(.:format)                           devise/passwords#update
# cancel_user_registration GET      /users/cancel(.:format)                             registrations#cancel
#        user_registration POST     /users(.:format)                                    registrations#create
#    new_user_registration GET      /users/sign_up(.:format)                            registrations#new
#   edit_user_registration GET      /users/edit(.:format)                               registrations#edit
#                          PATCH    /users(.:format)                                    registrations#update
#                          PUT      /users(.:format)                                    registrations#update
#                          DELETE   /users(.:format)                                    registrations#destroy
#                     user GET      /users/:id(.:format)                                users#show
#                    login GET      /login(.:format)                                    devise/sessions#new
#                   logout DELETE   /logout(.:format)                                   devise/sessions#destroy
#                 register GET      /register(.:format)                                 registrations#new
#                 settings GET      /settings(.:format)                                 devise/registrations#edit
#                 articles GET      /articles(.:format)                                 articles#index
#                          POST     /articles(.:format)                                 articles#create
#              new_article GET      /articles/new(.:format)                             articles#new
#             edit_article GET      /articles/:id/edit(.:format)                        articles#edit
#                  article GET      /articles/:id(.:format)                             articles#show
#                          PATCH    /articles/:id(.:format)                             articles#update
#                          PUT      /articles/:id(.:format)                             articles#update
#                          DELETE   /articles/:id(.:format)                             articles#destroy
#          previous_events GET      /events/previous(.:format)                          events#previous
#               map_events GET      /events/map(.:format)                               events#map
#                ics_event GET      /events/:id/ics(.:format)                           events#ics
#     event_event_partners POST     /events/:event_id/event_partners(.:format)          event_partners#create
#  new_event_event_partner GET      /events/:event_id/event_partners/new(.:format)      event_partners#new
# edit_event_event_partner GET      /events/:event_id/event_partners/:id/edit(.:format) event_partners#edit
#      event_event_partner PATCH    /events/:event_id/event_partners/:id(.:format)      event_partners#update
#                          PUT      /events/:event_id/event_partners/:id(.:format)      event_partners#update
#                          DELETE   /events/:event_id/event_partners/:id(.:format)      event_partners#destroy
#                   events GET      /events(.:format)                                   events#index
#                          POST     /events(.:format)                                   events#create
#                new_event GET      /events/new(.:format)                               events#new
#               edit_event GET      /events/:id/edit(.:format)                          events#edit
#                    event GET      /events/:id(.:format)                               events#show
#                          PATCH    /events/:id(.:format)                               events#update
#                          PUT      /events/:id(.:format)                               events#update
#                          DELETE   /events/:id(.:format)                               events#destroy
#                 partners GET      /partners(.:format)                                 partners#index
#                   venues GET      /venues(.:format)                                   venues#index
#                          POST     /venues(.:format)                                   venues#create
#                new_venue GET      /venues/new(.:format)                               venues#new
#               edit_venue GET      /venues/:id/edit(.:format)                          venues#edit
#                    venue GET      /venues/:id(.:format)                               venues#show
#                          PATCH    /venues/:id(.:format)                               venues#update
#                          PUT      /venues/:id(.:format)                               venues#update
#                          DELETE   /venues/:id(.:format)                               venues#destroy
#                 entities GET      /entities(.:format)                                 entities#index
#                          POST     /entities(.:format)                                 entities#create
#               new_entity GET      /entities/new(.:format)                             entities#new
#              edit_entity GET      /entities/:id/edit(.:format)                        entities#edit
#                   entity GET      /entities/:id(.:format)                             entities#show
#                          PATCH    /entities/:id(.:format)                             entities#update
#                          PUT      /entities/:id(.:format)                             entities#update
#                          DELETE   /entities/:id(.:format)                             entities#destroy
#               categories GET      /categories(.:format)                               categories#index
#                          POST     /categories(.:format)                               categories#create
#             new_category GET      /categories/new(.:format)                           categories#new
#            edit_category GET      /categories/:id/edit(.:format)                      categories#edit
#                 category GET      /categories/:id(.:format)                           categories#show
#                          PATCH    /categories/:id(.:format)                           categories#update
#                          PUT      /categories/:id(.:format)                           categories#update
#                          DELETE   /categories/:id(.:format)                           categories#destroy
#                     tags GET      /tags(.:format)                                     tags#index

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  slug             :string(255)
#  description      :text
#  venue_id         :integer
#  start_at         :datetime
#  end_at           :datetime
#  parent_id        :integer
#  logo             :string(255)
#  devcon_role      :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  summary          :text
#  schedule         :text
#  rules            :text
#  registration     :text
#  published        :boolean          default(FALSE)
#  event_type       :string(255)
#  target_attendees :integer
#  actual_attendees :integer
#  cover_photo      :string(255)
#

class Event < ActiveRecord::Base
  include ActionView::Helpers

  belongs_to :venue
  has_many :subevents, -> { order(:start_at) }, :class_name => "Event", :foreign_key => :parent_id
  belongs_to :parent, :class_name => "Event"
  has_many :event_partners
  has_many :entities, :through => :event_partners

  include SluggedResource
  include Icalendar

  mount_uploader :logo, ThumbnailUploader
  mount_uploader :cover_photo, CoverPhotoUploader

  scope :upcoming, -> { where("start_at > current_timestamp").order("start_at") }
  scope :current, -> { where("start_at <= current_timestamp and end_at >= current_timestamp").order("start_at") }
  scope :finished, -> { where("end_at < current_timestamp").order("end_at DESC") }
  scope :include_subevents, -> { where(:parent_id => nil).includes(:subevents) }

  def venues
    ([venue] + subevents.map { |e| e.venue }).compact.uniq
  end

  def effective_address
    if venue.nil?
      unless venues.empty?
        venues[0].address
      else
        nil
      end
    else
      venue.address
    end
  end

  def self.previous_by_month
    finished.include_subevents.group_by do |event|
      event.start_at.strftime("%B %Y")
    end
  end

  def google_calendar_url
    start_time = self.start_at.utc.strftime("%Y%m%dT%H%M00Z")
    end_time = self.end_at.utc.strftime("%Y%m%dT%H%M00Z")
    values = {
      action: 'TEMPLATE',
      text: self.name,
      dates: "#{start_time}/#{end_time}",
      details: truncate(strip_tags(HTMLEntities.new.decode(self.description)), length: 200),
      location: self.effective_address,
      trp: true,
      sprop: 'website:http://devcon.ph'
    }

    'http://google.com/calendar/event?' + values.to_query
  end

  def icalendar(event_url)
    event_temp = self
    cal = Calendar.new

    cal.event do |e|
      e.dtstart = event_temp.start_at.strftime("%Y%m%dT%H%M00")
      e.dtend = event_temp.end_at.strftime("%Y%m%dT%H%M00")
      e.summary = event_temp.name
      e.description = event_temp.summary
      e.ip_class = 'PRIVATE'
      e.url = event_url

      e.alarm do |a|
        a.action = 'DISPLAY'
        a.summary = 'Event notification'
        a.trigger = '-P1DT0H0M0S'
      end
    end

    cal.to_ical
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_resource :find_by => :slug
  load_and_authorize_resource :except => [:index, :previous, :ics, :map] 

  def index
    @current_events = Event.current.include_subevents
    @previous_events = Event.finished.include_subevents.limit(5)
    @previous_event_count = Event.finished.include_subevents.count
    @events = Event.upcoming.include_subevents.paginate(:page => params[:page])
  end

  def previous
    @previous_events = Event.previous_by_month
  end

  def new
  end

  def create
    if @event.save
      redirect_to event_path(@event), :notice => "Event successfully created"
    else
      render :new
    end
  end

  def show
    @hash = Gmaps4rails.build_markers(@event.venues) do |venue, marker|
      marker.lat venue.latitude
      marker.lng venue.longitude
      marker.infowindow render_to_string(:partial => "venues/infowindow", :layout => false, :locals => { :venue => venue })
      marker.json({ :id => venue.slug })
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to event_path(@event), :notice => "Event successfully updated"
    else
      render :edit
    end
  end

  def ics
    send_data @event.icalendar(event_url(@event)), filename: "#{@event.name}.ics", type: 'text/calendar', x_sendfile: true
  end

  def map
    @events = Event.select("DISTINCT ON (venue_id) *").where("venue_id IS NOT NULL").order("venue_id, end_at DESC").includes(:venue)
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      if event.end_at.future?
        marker.picture({
          :url => "http://mt.google.com/vt/icon?psize=30&font=fonts/arialuni_t.ttf&color=ff304C13&name=icons/spotlight/spotlight-waypoint-a.png&ax=43&ay=48&text=%E2%80%A2",
          :width   => 22,
          :height  => 40
        })
      end
      marker.lat event.venue.latitude
      marker.lng event.venue.longitude
      marker.infowindow render_to_string(:partial => "venues/infowindow_recent", :layout => false, :locals => { :event => event })
      marker.json({ :id => event.venue.slug })
    end
    render :map, :layout => false
  end

  private

    def event_params
      params.require(:event).permit(:description, :description, :devcon_role, :end_at, :logo, :cover_photo,
        :name, :parent_id, :slug, :start_at, :venue_id, :summary, :schedule, :rules, 
        :registration, :event_type, :target_attendees, :actual_attendees)
    end

end

app/views/events/_event.html.erb
<div class="row event">
  <div class="col-md-2 col-sm-3">
    <%= image_tag event.logo.thumb %>
  </div>
  <div class="col-md-10 col-sm-9">
    <h2><%= link_to event.name, event, :class => 'title' %></h2>
    <p><small>
      <%= l(event.start_at, :format => :long) %> 
      to
      <%= l(event.end_at, :format => :long) %> 
      <% if event.start_at.future? %>
        (<%= distance_of_time_in_words_to_now event.start_at %> from now)
      <% end %>
      |
      <%= link_to "", event_url(event) + "#disqus_thread" %>
    </small></p>
    <p class="summary">
      <%= event.summary %>
      <% if can? :manage, Event %>
        <%= link_to "Edit", edit_event_path(event), :class => "btn btn-default btn-xs" %>
        <%= link_to "Destroy", event, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger btn-xs" %>
      <% end %>
    </p>
    <% unless event.subevents.empty? %>
      <p class="parent-note">This event is made up of the following sub-events:</p>
      <% event.subevents.each do |subevent| %>
        <h3 class="parent-note"><%= link_to subevent.name, subevent %></li>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/_event_partner.html.erb
<% entity = event_partner.entity %>
<div class="row">
  <% unless entity.logo.blank? %>
    <div class="col-lg-2 col-md-2 col-sm-2">
      <%= image_tag entity.logo.medium.url %>
    </div>
    <div class="col-lg-10 col-md-10 col-sm-10">
  <% else %>
    <div class="col-lg-12 col-md-12 col-sm-12">
  <% end %>
    <h3 class="subtitle"><%= link_to entity.name, entity %></h2>
    <h4 class="role"><%= event_partner.role %></h4>
    <% if event_partner.custom_blurb.blank? %>
      <%= raw entity.blurb %>
    <% else %>  
      <%= raw event_partner.custom_blurb %>
    <% end %>
    <% if can? :manage, EventPartner %>
      <p><%= link_to "Edit Event Partner", edit_event_event_partner_path(event_partner.event, event_partner), :class => "btn btn-default" %></p>
    <% end %>  
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event,
    :wrapper_mappings => {
      :check_boxes => :vertical_radio_and_checkboxes,
      :radio_buttons => :vertical_radio_and_checkboxes,
      :file => :vertical_file_input,
      :boolean => :vertical_boolean }) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <%= f.input :name %>
  <% unless @event.new_record? %>
    <%= f.input :slug %>
  <% end %>
  <%= f.association :parent %>
  <%= f.input :logo, :as => :file, :hint => "a square logo, at least 200px x 200px" %>
  <%= f.input :cover_photo, :as => :file, :hint => "at least 940px x 315px" %>
  <%= f.input :summary, :input_html => { class: 'input-xxlarge editor-html', size: "500x6" } %>
  <%= f.association :venue %>
  <%= f.input :start_at, :as => :string, :input_html => { :class => "datetimepicker", :value => text_field_datetime(@event.start_at) } %>
  <%= f.input :end_at, :as => :string, :input_html => { :class => "datetimepicker", :value =>  text_field_datetime(@event.end_at) } %>
  <%= f.input :description, :as => :ckeditor %>
  <%= f.input :schedule, :as => :ckeditor %>
  <%= f.input :rules, :as => :ckeditor %>
  <%= f.input :registration, :as => :ckeditor %>
  <%= f.input :devcon_role %>
  <%= f.input :event_type %>
  <%= f.input :target_attendees, :label => "No. of target attendees" %>
  <%= f.input :actual_attendees, :label => "No. of actual attendees" %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/events/_gmaps.html.erb
<%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" %>
<%= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
<script type="text/javascript">
  handler = Gmaps.build('Google', { markers: { maxRandomDistance: null } });
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(14);
  });
</script>

app/views/events/_participant.html.erb
<% rp = participant.resource_person %>
<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-3">
    <% unless rp.thumbnail.blank? %>
      <%= image_tag rp.thumbnail.thumb.url %>
    <% end %>
  </div>
  <div class="span9">
    <h3 class="subtitle"><%= link_to rp.name, rp %></h2>
    <h4 class="role"><%= participant.role %></h4>
    <h4 class="person-title">
      <% if participant.custom_title.blank? %>
        <%= raw rp.main_title %>
      <% else %>
        <%= raw participant.custom_title %>
      <% end %>
    </h4>
    <% if participant.custom_description.blank? %>
      <%= raw rp.description %>
    <% else %>
      <%= raw participant.custom_description %>
    <% end %>
    <% if can? :manage, EventPartner %>
      <p><%= link_to "Edit Participant", edit_event_participant_path(participant.event, participant), :class => "btn" %></p>
    <% end %>  
  </div>
</div>

app/views/events/edit.html.erb
<% title 'Edit Event' %>
<h1>Edit Event</h1>

<%= render 'form' %>
<%= link_to 'Back to events', events_path %>

app/views/events/index.html.erb
<% title 'Events' %>
<% description "Know about our upcoming events! You can also browse our past events." %>
<% set_meta_tags :open_graph => {
  :title => "Events | #{ENV['title']}",
  :description => "Know about our upcoming events! You can also browse our past events.",
  :type  => :article,
  :url   => events_url,
  :image => opengraph_thumb_url
} %>
<h1>Events</h1>

<%= link_to 'Event Map', map_events_path, :class => 'btn btn-default' %>
<%= link_to 'iCalendar', calendar_path, :class => 'btn btn-default' %>

<% if can? :create, Event %>
  <%= link_to 'New event', new_event_path, :class => "btn btn-default" %>
<% end %>

<% unless @current_events.empty? %>
  <div class="row">
    <div class="col-sm-12">
      <h2>Ongoing Events</h2>
    </div>
  </div>
  <%= render @current_events %>
<% end %>
<div class="row">
  <div class="col-sm-12">
    <h2>Upcoming Events</h2>
  </div>
</div>
<% unless @events.empty? %>
  <%= render @events %>
<% else %>
  <p>
    We have no upcoming events.<br>
    <%= link_to "Learn how to receive notifications about upcoming events.", notifications_path %></p>
<% end %>
<% unless @previous_events.empty? %>
  <div class="row">
    <div class="col-sm-12">
      <h2>Previous Events</h2>
    </div>
  </div>
  <% @previous_events.each do |event| %>
    <div class="row previous-event">
      <div class="col-sm-12">
        <h2><%= link_to event.name, event, :class => 'title' %></h2>
      </div>
    </div>
  <% end %>
  <% if @previous_event_count > 5 %>
    <div class="row">
      <div class="col-sm-12">
        <p><%= link_to 'view more previous events...', previous_events_path %></p>
      </div>
    </div>
  <% end %>
<% end %>

<%= render :partial => "shared/disqus_count" %>

app/views/events/map.html.erb
<% title "Events Map" %>
<% description "Map of recent events conducted by DevCon" %>
<% set_meta_tags :open_graph => {
  :title => "Events Map",
  :description => "Map of recent events conducted by DevCon",
  :type  => :website,
  :url   => map_events_url,
  :image => [opengraph_thumb_url, { :width => 200, :height => 200 }]
} %>
<!DOCTYPE html>
<html style="height:100%">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="fb:admins" content="100000251664444" />
    <%= display_meta_tags :site => ENV['title'], :reverse => true %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <link href="/favicon.ico" rel="shortcut icon">
    <link href="/apple-touch-icon-144-precomposed.png" sizes="144x144" rel="apple-touch-icon-precomposed">
    <link href="/apple-touch-icon-114-precomposed.png" sizes="114x114" rel="apple-touch-icon-precomposed">
    <link href="/apple-touch-icon-72-precomposed.png" sizes="72x72" rel="apple-touch-icon-precomposed">
    <link href="/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon-precomposed">
    <%= auto_discovery_link_tag :atom, "/feed" %>
    <%= auto_discovery_link_tag :rss, "/feed.rss" %>
  </head>
  <body style="height:100%">
    <%= render 'layouts/header' %>
    <div id="map" style="height:100%;overflow-y:hidden;margin-top:-5px;margin-left:5px;margin-right:5px">
      <%= yield %>
    </div>
    <%= render 'layouts/analytics' %>
    <% if user_signed_in? and (current_user.role?("admin") or current_user.role?("author")) %>
      <%= javascript_include_tag "admin" %>
    <% else %>
      <%= javascript_include_tag "application" %>
    <% end %>
    <%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" %>
    <%= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <script type="text/javascript">
      handler = Gmaps.build('Google', { markers: { maxRandomDistance: null } });
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.map.centerOn([12, 120.9822000]);
        handler.getMap().setZoom(6);
      });
    </script>
  </body>
</html>

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>
<h1>New Event</h1>

<%= render 'form' %>
<%= link_to 'Back to events', events_path %>

app/views/events/previous.html.erb
<% title 'Previous Events' %>
<% description "Know about our past events!" %>
<% set_meta_tags :open_graph => {
  :title => "Previous Events | #{ENV['title']}",
  :description => "Know about our past events!",
  :type  => :article,
  :url   => previous_events_url,
  :image => opengraph_thumb_url
} %>
<h1>Previous Events</h1>

<% @previous_events.each do |month, event_group| %>
  <h2><%= month %></h2>
  <% event_group.reverse.each do |event| %>
    <div class="row previous-event">
      <div class="col-sm-12">
        <h3><%= link_to event.name, event, :class => 'title' %></h2>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row go-back">
  <div class="col-sm-12">
    <p><%= link_to 'Go back events list', events_path %></p>
  </div>
</div>

app/views/events/show.html.erb
<% title @event.name %>
<% description generate_description(@event.summary) %>
<% set_meta_tags :open_graph => {
  :title => "#{@event.name} | #{ENV['title']}",
  :description => generate_description(@event.summary),
  :type  => :article,
  :url   => event_url(@event),
  :image => [thumbnail_url(@event), { :width => 200, :height => 200 }]
} %>
<% content_for :scripts do %>
  <%= render "gmaps" %>
<% end %>

<div class="row event">
  <div class="col-md-12">
    <% cache [@event, "title"] do %>
    <div class="row">
      <div class="col-md-12">
        <%= image_tag @event.cover_photo.cover.url %>
        <h1><%= link_to @event.name, @event, :class => 'title' %></h2>
        <p><small>
          <%= l(@event.start_at, :format => :long) %> 
          to
          <%= l(@event.end_at, :format => :long) %> 
        </small></p>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <% cache [@event, "description"] do %>
        <% if @event.parent %>
          <p class="parent-note">Part of <%= link_to "#{@event.parent.name}", @event.parent %></p>
        <% end %>  
        <%= raw @event.description %>
        <% unless @event.subevents.empty? %>
          <p class="parent-note">This event is made up of the following sub-events:</p>
          <ul>
          <% @event.subevents.each do |subevent| %>
            <li class="parent-note"><%= link_to subevent.name, subevent %></li>
          <% end %>
          </ul>
        <% end %>
        <% end %>
        <% if can? :manage, Event %>
          <p>
            <%= link_to "Edit", edit_event_path(@event), :class => 'btn btn-default' %>
          </p>
        <% end %>
      </div>
    </div>
    <% unless @event.venues.empty? %>
      <div class="row">
        <div class="col-md-12">
          <h2 class="subtitle">Where &amp; When</h2>
          <div class="map_container">
            <div id="map" class="gmaps4rails_map"></div>
          </div>
          <% unless @event.venue.nil? %>
            <h3><%= @event.venue.name %></h3>
            <%= simple_format @event.venue.address %>
            <p>
              <%= l(@event.start_at, :format => :long) %> 
              to
              <%= l(@event.end_at, :format => :long) %> 
            </p>
          <% end %>
          <% @event.subevents.each do |subevent| %>
            <h3><%= subevent.name %> - <%= subevent.venue.name %></h3>
            <%= simple_format subevent.venue.address %>
            <p>
              <%= l(subevent.start_at, :format => :long) %> 
              to
              <%= l(subevent.end_at, :format => :long) %> 
            </p>
          <% end %>
        </div>
      </div>
    <% end %>
    <% cache [@event, "rest-of-page"] do %>
    <% unless @event.event_partners.empty? %>
      <div class="row">
        <div class="col-md-12">
          <h2 class="subtitle">Partners</h2>
        </div>
      </div>
      <%= render :partial => "event_partner", :collection => @event.event_partners %>
    <% end %>
    <div class="row">
      <% unless @event.schedule.blank? %>
        <div class="col-md-12">
          <h2 class="subtitle">Schedule</h2>
          <%= raw @event.schedule %>
        </div>
      <% end %>
    </div>
    <% unless @event.rules.blank? %>
      <div class="row">
        <div class="col-md-12">
          <h2 class="subtitle">Rules</h2>
          <%= raw @event.rules %>
        </div>
      </div>
    <% end %>
    <% unless @event.registration.blank? %>
      <div class="row">
        <div class="col-md-12">
          <h2 class="subtitle">Registration</h2>
          <%= raw @event.registration %>
        </div>
      </div>
    <% end %>
    <hr>
    <div class="row social-sharing">
      <%= render "shared/social_sharing" %>
      <div class="col-sm-5">
        <%= link_to 'Google Calendar', @event.google_calendar_url, :class => 'btn btn-default btn-xs' %>
        <%= link_to 'iCalendar', ics_event_path(@event), :class => 'btn btn-default btn-xs' %>
      </div>
    </div>
    <div id="disqus_thread"></div>
    <% end %>
  </div>
</div>
<% cache [@event, "comments"] do %>
<%= render :partial => "shared/disqus_comments" %>
<% end %>